# Generated by Django 5.0.2 on 2024-05-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_amount',
            field=models.IntegerField(default=0),
        ),
    ]
