# Generated by Django 5.0.2 on 2024-05-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_coupon_min_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expiration_date',
        ),
    ]
