# Generated by Django 5.0.2 on 2024-05-07 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_coupon_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coupon'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_amount',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
