# Generated by Django 5.0.2 on 2024-05-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='add_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
